apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergychat-crawler
  labels:
    app: synergychat-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synergychat-crawler
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: synergychat-crawler
    spec:
      containers:
      - image: bootdotdev/synergychat-crawler:latest
        imagePullPolicy: Always
        name: synergychat-crawler-1
        env:
          - name: CRAWLER_PORT
            valueFrom: 
              configMapKeyRef: 
                name: synergychat-crawler-configmap
                key: CRAWLER_PORT
          - name: CRAWLER_KEYWORDS
            valueFrom: 
              configMapKeyRef: 
                name: synergychat-crawler-configmap
                key: CRAWLER_KEYWORDS
          - name: CRAWLER_DB_PATH
            valueFrom: 
              configMapKeyRef: 
                name: synergychat-crawler-configmap
                key: CRAWLER_DB_PATH
        volumeMounts:
          - name: cache-volume
            mountPath: /cache
          - name: synergychat-api-volume
            mountPath: /persist
      - image: bootdotdev/synergychat-crawler:latest
        imagePullPolicy: Always
        name: synergychat-crawler-2
        env:
          - name: CRAWLER_PORT
            valueFrom: 
              configMapKeyRef: 
                name: synergychat-crawler-configmap
                key: CRAWLER_PORT_2
          - name: CRAWLER_KEYWORDS
            valueFrom: 
              configMapKeyRef: 
                name: synergychat-crawler-configmap
                key: CRAWLER_KEYWORDS
          - name: CRAWLER_DB_PATH
            valueFrom: 
              configMapKeyRef: 
                name: synergychat-crawler-configmap
                key: CRAWLER_DB_PATH
        volumeMounts:
          - name: cache-volume
            mountPath: /cache
          - name: synergychat-api-volume
            mountPath: /persist
      - image: bootdotdev/synergychat-crawler:latest
        imagePullPolicy: Always
        name: synergychat-crawler-3
        env:
          - name: CRAWLER_PORT
            valueFrom: 
              configMapKeyRef: 
                name: synergychat-crawler-configmap
                key: CRAWLER_PORT_3
          - name: CRAWLER_KEYWORDS
            valueFrom: 
              configMapKeyRef: 
                name: synergychat-crawler-configmap
                key: CRAWLER_KEYWORDS
          - name: CRAWLER_DB_PATH
            valueFrom: 
              configMapKeyRef: 
                name: synergychat-crawler-configmap
                key: CRAWLER_DB_PATH
        volumeMounts:
          - name: cache-volume
            mountPath: /cache
          - name: synergychat-api-volume
            mountPath: /persist
      volumes:
        - name: cache-volume
          emptyDir: {}
        - name: synergychat-api-volume
          persistentVolumeClaim:
            claimName: synergychat-api-pvc

